; PlatformIO Project Configuration File for ESP32 SH1106 OLED Test

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    olikraus/U8g2@^2.35.9
    https://github.com/ricmoo/QRCode.git
