; PlatformIO Project Configuration File
; Arduino Uno OLED Test

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200

lib_deps =
    olikraus/U8g2@^2.35.9

; Build only test_oled.cpp
build_src_filter = -<*> +<test_oled.cpp>
