; Smart QR Payment - ESP32 firmware (OLED + Loa MAX98357A)
; platform 6.9.0 = Arduino core 2.x, tuong thich ESP32-audioI2S 2.0.6

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

board_build.partitions = partitions.csv
board_build.filesystem = littlefs

lib_deps =
    olikraus/U8g2@^2.35.9
    https://github.com/ricmoo/QRCode.git
    https://github.com/schreibfaul1/ESP32-audioI2S.git#2.0.6